version: 2
updates:
  - package-ecosystem: npm
    directory: "/client"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 1

  - package-ecosystem: "cargo"
    directory: "/client/src-tauri"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Ho_Chi_Minh"
    open-pull-requests-limit: 1
    commit-message:
      prefix: "deps"
      include: "scope"
    groups:
      all:
        patterns:
          - "*"
    labels:
      - "dependencies"
      - "rust"
    reviewers:
      - "dependabot-preview[bot]"
    target-branch: "main"
    ignore:
      - dependency-name: "tokio"
        update-types:
          - "version-update:semver-minor"
          - "version-update:semver-patch"
