from enum import Enum


class Decision(str, Enum):
    VERIFIED = "VERIFIED"
    RETRY_ALLOWED = "RETRY_ALLOWED"
    FAILED_FINAL = "FAILED_FINAL"
    SYSTEM_ERROR = "SYSTEM_ERROR"


class ReasonCode(str, Enum):
    CCCD_IMAGE_QUALITY_LOW = "CCCD_IMAGE_QUALITY_LOW"
    CCCD_PORTRAIT_NOT_FOUND = "CCCD_PORTRAIT_NOT_FOUND"
    LIVE_FACE_NOT_FOUND = "LIVE_FACE_NOT_FOUND"
    MULTIPLE_FACES_DETECTED = "MULTIPLE_FACES_DETECTED"
    LIVE_VIDEO_QUALITY_LOW = "LIVE_VIDEO_QUALITY_LOW"
    FACE_OCCLUDED = "FACE_OCCLUDED"
    LIVENESS_CHALLENGE_FAILED = "LIVENESS_CHALLENGE_FAILED"
    LIVENESS_NOT_CONFIDENT = "LIVENESS_NOT_CONFIDENT"
    FACE_MISMATCH = "FACE_MISMATCH"
    SESSION_EXPIRED = "SESSION_EXPIRED"
    RATE_LIMITED = "RATE_LIMITED"
    INTERNAL_ERROR = "INTERNAL_ERROR"


class SessionStatus(str, Enum):
    IN_PROGRESS = "IN_PROGRESS"
    VERIFIED = "VERIFIED"
    FAILED_FINAL = "FAILED_FINAL"
    EXPIRED = "EXPIRED"
