[package]
name = "anomaly_admin"
version = "0.1.0"
description = "Anomaly Admin Console"
authors = ["AnomalyBank"]
edition = "2021"

[lib]
name = "anomaly_admin_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[profile.release]
codegen-units = 1
lto = true
opt-level = 3
panic = "abort"
strip = true
